framework:
    notifier:
        chatter_transports:
        texter_transports:
            twilio: '%env(NOTIFIER_DSN)%'
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['sms']
            high: ['sms']
            medium: ['sms']
            low: ['sms']
        admin_recipients:
            - { email: admin@example.com }
