parameters:
  user_images_directory: '%kernel.project_dir%/public/uploads/user_images'
  cv_directory: '%kernel.project_dir%/public/uploads/cv'
  RECAPTCHA_SECRET_KEY: '%env(string:RECAPTCHA3_SECRET)%'
  RECAPTCHA_SITE_KEY: '%env(string:RECAPTCHA3_KEY)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Injection du Client Mailjet
  Mailjet\Client:
    arguments:
      $key:     '%env(MAILJET_APIKEY)%'
      $secret:  '%env(MAILJET_SECRET)%'
      $settings:
        version: 'v3.1'

  App\Service\SmsSender:
    arguments:
      $twilioSid:   '%env(string:TWILIO_SID)%'
      $twilioToken: '%env(string:TWILIO_AUTH_TOKEN)%'
      $from:        '%env(string:TWILIO_PHONE_NUMBER)%'

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'